# Generated by Django 3.2.3 on 2021-06-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('het_article', models.BooleanField(default=False)),
                ('de_article', models.BooleanField(default=False)),
                ('polish', models.CharField(max_length=50)),
                ('english', models.CharField(max_length=50)),
            ],
        ),
    ]
