# Generated by Django 3.2.3 on 2021-06-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='dutch',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
