# Generated by Django 3.2.3 on 2021-06-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_word_dutch'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
