# Generated by Django 3.2.3 on 2021-06-03 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_word_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='english',
        ),
    ]
