# Generated by Django 4.0.3 on 2022-04-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_word_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='english',
        ),
    ]
